name: Validate Aura workbook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run workbook validation
        run: |
          pytest -q

      - name: Show workbook validation report (if present)
        if: always()
        run: |
          python -c "from src.file_loader import validate_workbook; import json; ok, r = validate_workbook('data/Aura.xlsl'); print(json.dumps(r, indent=2))"
